name: Deploy to PM_SB on Merge

on:
  push:
    branches:
      - development-changes-third-step

jobs:
  deploy:
    if: github.ref == 'refs/heads/deployment-changes-second-step'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli --global
        sfdx --version

    - name: Authenticate to PM_SB using Auth URL
      run: |
          echo "${{ secrets.PM_SB_AUTH_URL }}" > auth.txt
          sfdx force:auth:sfdxurl:store -f auth.txt -a PM_SB
          sfdx force:org:list
      shell: bash

    - name: Validate metadata deployment
      run: |
        sfdx force:source:deploy -u PM_SB -p force-app --checkonly --json --loglevel fatal
      shell: bash


    - name: Deploy metadata to Priyankar
      run: |
        sfdx force:source:deploy -u PM_SB -p force-app --json --loglevel fatal
